server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
              - X-Trace-Id
              - X-User-Id
              - X-User-Email
              - X-Roles
              - X-Permissions
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**

        - id: borrow-service
          uri: lb://borrow-service
          predicates:
            - Path=/api/borrow-records/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**,/api/internal/notifications/**

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/dashboard/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: BVvt2Q2OaZHShF3oCXuRVVTDEPkdu0e6KAvgOriLCA5TH9mDqPI94L81U24gyUT9vKyN0v5i2WbSPpiegonSQD
  expiration: 86400000


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG