server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    username: postgres
    password: admin

  flyway:
    enabled: true
    locations: classpath:db/migration/schema
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


services:
  user-service:
    url: http://localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: BVvt2Q2OaZHShF3oCXuRVVTDEPkdu0e6KAvgOriLCA5TH9mDqPI94L81U24gyUT9vKyN0v5i2WbSPpiegonSQD
  expiration: 86400000


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG